'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

const activityTypes=['Training / Workshop','School Session','Community Outreach','Awareness Activity','Mentorship Session','Meeting','Campaign / Event','Other'];
const fundingTypes=['Donor-funded','VSI internal funding','Partner-funded','Jointly funded','Other'];
const implementationTypes=['Fully implemented','Partially implemented','Not implemented'];
const safeguardingTypes=['No concerns identified','Concern identified and handled according to VSI procedures','Concern requires follow-up'];
const budgetStatuses=['Within approved budget','Underspent','Overspent'];
const assessmentTypes=['Excellent','Good','Satisfactory','Needs Improvement'];
const evidenceTypes=['Attendance / participant register','Photos','Training / presentation materials','Participant feedback','Pre/post assessment','Financial documentation','Receipts','Referral / follow-up documentation','Other'];

const blank={activityTitle:'',activityDate:'',startTime:'',endTime:'',activityType:'',activityTypeOther:'',directorate:'',programme:'',project:'',activityCode:'',activitySdgs:'',activityAuAgenda2063:'',activityDescription:'',province:'',district:'',constituency:'',wardCommunity:'',venue:'',reporterFullName:'',reporterPosition:'',reporterPhone:'',reporterEmail:'',supervisorFullName:'',supervisorPosition:'',supervisorPhone:'',supervisorEmail:'',donorName:'',grantTitle:'',grantReference:'',grantManager:'',grantPhone:'',grantEmail:'',fundingSource:'',fundingSourceOther:'',leadFacilitator:'',otherStaffVolunteers:'',partnerOrganisations:'',partnerContact:'',plannedMaleChildren:'',plannedMaleYouth:'',plannedMaleAdult:'',plannedFemaleChildren:'',plannedFemaleYouth:'',plannedFemaleAdult:'',plannedPwdMaleChildren:'',plannedPwdMaleYouth:'',plannedPwdMaleAdult:'',plannedPwdFemaleChildren:'',plannedPwdFemaleYouth:'',plannedPwdFemaleAdult:'',reachedMaleChildren:'',reachedMaleYouth:'',reachedMaleAdult:'',reachedFemaleChildren:'',reachedFemaleYouth:'',reachedFemaleAdult:'',reachedPwdMaleChildren:'',reachedPwdMaleYouth:'',reachedPwdMaleAdult:'',reachedPwdFemaleChildren:'',reachedPwdFemaleYouth:'',reachedPwdFemaleAdult:'',participantPerformanceJustification:'',objectives:'',activityDelivered:'',implementationStatus:'',implementationChange:'',knowledgeSkills:'',keyIssues:'',participantFeedback:'',immediateOutcomes:'',notableAchievements:'',resultsEvidence:'',challenges:'',challengesAddressed:'',lessonsLearned:'',futureImprovements:'',safeguardingStatus:'',safeguardingDescription:'',safeguardingMeasures:'',overallAssessment:'',assessmentExplanation:'',evidenceUploaded:'',photoMediaConsent:'',declaration:false};

function Section({n,title,description,children}){return <section className="section"><div className="section-head"><span className="number">{n}</span><div><h2>{title}</h2><p>{description}</p></div></div><div className="section-body">{children}</div></section>}
function Field({label,name,form,setForm,type='text',readOnly=false,className=''}){return <label className={className}>{label}<input type={type} name={name} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})} readOnly={readOnly}/></label>}
function Text({label,name,form,setForm,className=''}){return <label className={className}>{label}<textarea name={name} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>}
function Select({label,name,form,setForm,options}){return <label>{label}<select name={name} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}><option value="">Select</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>}

const rows=[['Male','plannedMaleChildren','plannedMaleYouth','plannedMaleAdult'],['Female','plannedFemaleChildren','plannedFemaleYouth','plannedFemaleAdult'],['PWD Male','plannedPwdMaleChildren','plannedPwdMaleYouth','plannedPwdMaleAdult'],['PWD Female','plannedPwdFemaleChildren','plannedPwdFemaleYouth','plannedPwdFemaleAdult']];
const reachedRows=[['Male','reachedMaleChildren','reachedMaleYouth','reachedMaleAdult'],['Female','reachedFemaleChildren','reachedFemaleYouth','reachedFemaleAdult'],['PWD Male','reachedPwdMaleChildren','reachedPwdMaleYouth','reachedPwdMaleAdult'],['PWD Female','reachedPwdFemaleChildren','reachedPwdFemaleYouth','reachedPwdFemaleAdult']];

export default function CleanActivityReport(){
 const [form,setForm]=useState(blank);const [activitySearch,setActivitySearch]=useState('');const [results,setResults]=useState([]);const [searching,setSearching]=useState(false);const [evidence,setEvidence]=useState([]);const [files,setFiles]=useState([]);const [budgetItems,setBudgetItems]=useState([{item:'',approved:'',actual:''}]);const [followUps,setFollowUps]=useState([{action:'',responsible:'',deadline:'',status:'Pending'}]);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [submitted,setSubmitted]=useState('');const fileRef=useRef(null);
 const set=p=>setForm(x=>({...x,...p}));
 useEffect(()=>{const q=activitySearch.trim();if(!q){setResults([]);return}const c=new AbortController();const t=setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/activities/approved?search=${encodeURIComponent(q)}`,{signal:c.signal});const d=await r.json();setResults(r.ok&&Array.isArray(d.activities)?d.activities:[])}catch(e){if(e.name!=='AbortError')setResults([])}finally{if(!c.signal.aborted)setSearching(false)}},250);return()=>{clearTimeout(t);c.abort()}},[activitySearch]);
 const selectActivity=a=>{set({activityTitle:a.name||a.activityName||'',activityCode:a.code||a.activityCode||'',project:a.project||'',programme:a.programme||'',directorate:a.directorate||'',activitySdgs:a.unSdgsAlignment||a.sdgsAlignment||'',activityAuAgenda2063:a.auAgenda2063Alignment||''});setActivitySearch('');setResults([])};
 const planned=rows.reduce((s,r)=>s+r.slice(1).reduce((x,k)=>x+(Number(form[k])||0),0),0);const reached=reachedRows.reduce((s,r)=>s+r.slice(1).reduce((x,k)=>x+(Number(form[k])||0),0),0);const achievement=planned?Math.round(reached/planned*100):0;const performance=planned?(reached<planned?'UNDER-ACHIEVED':reached>planned?'OVER-ACHIEVED':'ACHIEVED'):'';const totals=useMemo(()=>({approved:budgetItems.reduce((s,x)=>s+(Number(x.approved)||0),0),actual:budgetItems.reduce((s,x)=>s+(Number(x.actual)||0),0)}),[budgetItems]);const variance=totals.approved-totals.actual;const selectedBudget=variance>0?'Underspent':variance<0?'Overspent':'Within approved budget';
 async function submit(e){e.preventDefault();setError('');setSaving(true);try{const attachments=[];for(const file of files){const fd=new FormData();fd.append('file',file);fd.append('reference',`PENDING-${crypto.randomUUID().slice(0,8).toUpperCase()}`);const r=await fetch('/api/activity-reports/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||`Unable to upload ${file.name}.`);attachments.push({name:d.name,type:d.type,size:d.size,url:d.url,pathname:d.pathname,category:'evidence'})}const payload={...form,plannedParticipantTotal:planned,reachedParticipantTotal:reached,participantPerformance:performance,participantPerformancePercent:achievement,participantTotal:reached,approvedBudget:totals.approved,actualSpent:totals.actual,budgetStatus:form.budgetStatus||selectedBudget,budgetItems,followUpActions:followUps,evidenceAvailable:evidence,attachments};const r=await fetch('/api/activity-reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to submit the report.');setSubmitted(d.reference)}catch(e){setError(e.message)}finally{setSaving(false)}}
 if(submitted)return <main className="page"><div className="shell"><div className="success"><div className="success-mark">✓</div><p className="kicker">REPORT RECEIVED</p><h1>Activity report submitted.</h1><p>Your report has been received by VSI and is now recorded for review.</p><div className="ref">{submitted}</div></div></div></main>;
 const ParticipantTable=({title,data})=><div className="participant-panel"><div className="participant-panel-title">{title}</div><div className="participant-table"><div className="participant-row participant-header"><span>Category</span><span>Children</span><span>Youth</span><span>Adult</span></div>{data.map(r=><div className="participant-row" key={r[0]}><strong>{r[0]}</strong>{r.slice(1).map(k=><input key={k} type="number" min="0" value={form[k]||''} onChange={e=>set({[k]:e.target.value})}/>)}</div>)}</div></div>;
 return <main className="page"><div className="topbar"><div className="topbar-inner"><div className="brand"><img src="/VSI%20LOGO%20white.png" alt="Visionary Students Initiative" className="vsi-logo"/><small>VISIONARY STUDENTS INITIATIVE</small></div><span>ACTIVITY REPORT</span><nav className="social-links"><a href="https://web.facebook.com/vsizambia">f</a><a href="https://www.linkedin.com/in/visionary-students-initiative-vsi-0a447238/">in</a><a href="https://www.instagram.com/vsizambia">◎</a><a href="https://www.youtube.com/@vsizambia">▶</a><a href="https://www.vsizambia.org">↗</a></nav></div></div><div className="shell"><header className="form-intro"><p>Complete this report after an activity implemented by VSI. All activity information is entered by the reporting officer. Please provide accurate information and attach supporting evidence where available.</p></header><form onSubmit={submit} noValidate>
 <Section n="01" title="Activity Identification" description="Search and select the approved VSI activity being reported."><div className="grid"><div className="full"><label>Search approved VSI activity</label><input value={activitySearch} onChange={e=>setActivitySearch(e.target.value)} placeholder="Search by activity name or activity code…" autoComplete="off"/>{activitySearch.trim()&&<div className="activity-results" role="listbox">{searching?<div className="hint">Searching approved activities…</div>:results.length?results.slice(0,8).map((a,i)=><button type="button" className="activity-result" key={a.code||a.activityCode||i} onClick={()=>selectActivity(a)}><strong>{a.code||a.activityCode}</strong><span>{a.name||a.activityName}</span><small>{a.project||'—'} · {a.directorate||'—'}</small></button>):<div className="hint">No approved activity found.</div>}</div>}</div><Field label="Activity Code" name="activityCode" form={form} setForm={set} readOnly/><Field label="Activity Name" name="activityTitle" form={form} setForm={set} readOnly/><Field label="Programme" name="programme" form={form} setForm={set} readOnly/><Field label="Project" name="project" form={form} setForm={set} readOnly/><Field label="Directorate" name="directorate" form={form} setForm={set} readOnly/><Field label="UN SDGs Alignment" name="activitySdgs" form={form} setForm={set} readOnly/><Field label="AU Agenda 2063 Alignment" name="activityAuAgenda2063" form={form} setForm={set} readOnly/><Field label="Activity Date" name="activityDate" form={form} setForm={set} type="date"/><Field label="Start Time" name="startTime" form={form} setForm={set} type="time"/><Field label="End Time" name="endTime" form={form} setForm={set} type="time"/><Select label="Activity Type" name="activityType" form={form} setForm={set} options={activityTypes}/>{form.activityType==='Other'&&<Field label="Other activity type" name="activityTypeOther" form={form} setForm={set}/>}<Text label="Brief description of the activity" name="activityDescription" form={form} setForm={set} className="full"/></div></Section>
 <Section n="02" title="Activity Location" description="Record where the activity took place."><div className="grid"><Field label="Province" name="province" form={form} setForm={set}/><Field label="District" name="district" form={form} setForm={set}/><Field label="Constituency" name="constituency" form={form} setForm={set}/><Field label="Ward / Community" name="wardCommunity" form={form} setForm={set}/><Field label="Specific Venue / Location" name="venue" form={form} setForm={set} className="full"/></div></Section>
 <Section n="03" title="Reporting Officer" description="Enter the reporting officer and supervisor information."><div className="grid"><Field label="Full Name" name="reporterFullName" form={form} setForm={set}/><Field label="Position / Role" name="reporterPosition" form={form} setForm={set}/><Field label="Phone Number" name="reporterPhone" form={form} setForm={set} type="tel"/><Field label="Email Address" name="reporterEmail" form={form} setForm={set} type="email"/><Field label="Supervisor's Full Name" name="supervisorFullName" form={form} setForm={set}/><Field label="Position / Role" name="supervisorPosition" form={form} setForm={set}/><Field label="Phone Number" name="supervisorPhone" form={form} setForm={set} type="tel"/><Field label="Email Address" name="supervisorEmail" form={form} setForm={set} type="email"/></div></Section>
 <Section n="04" title="Funding & Partners" description="Record funding, facilitators and partner organisations involved in implementation."><div className="grid"><Select label="Funding Source" name="fundingSource" form={form} setForm={set} options={fundingTypes}/><Field label="Donor Name" name="donorName" form={form} setForm={set}/><Field label="Project / Grant Title" name="grantTitle" form={form} setForm={set}/><Field label="Grant / Project Reference" name="grantReference" form={form} setForm={set}/><Field label="Grant Manager / Donor Contact" name="grantManager" form={form} setForm={set}/><Field label="Grant Manager Phone" name="grantPhone" form={form} setForm={set}/><Field label="Grant Manager Email" name="grantEmail" form={form} setForm={set}/><Field label="Lead Facilitator" name="leadFacilitator" form={form} setForm={set}/><Field label="Other VSI Staff / Volunteers Involved" name="otherStaffVolunteers" form={form} setForm={set}/><Field label="Partner Organisation(s)" name="partnerOrganisations" form={form} setForm={set}/><Field label="Partner Contact Person" name="partnerContact" form={form} setForm={set}/></div></Section>
 <Section n="05" title="Participants & Attendance" description="Record participation and demographic information. Attendance documents are uploaded once in Section 09."><div className="participant-panels"><ParticipantTable title="PLANNED PARTICIPANTS" data={rows}/><ParticipantTable title="REACHED PARTICIPANTS" data={reachedRows}/></div><div className="participant-performance"><div><span>PERFORMANCE</span><strong>{performance||'Awaiting participant figures'}</strong></div><div><span>ACHIEVEMENT</span><strong>{planned?`${achievement}%`:'—'}</strong></div><div><span>VARIANCE</span><strong>{planned?reached-planned:'—'}</strong></div></div>{(performance==='UNDER-ACHIEVED'||performance==='OVER-ACHIEVED')&&<Text label="Justification for performance variance" name="participantPerformanceJustification" form={form} setForm={set} className="full"/>}<div className="participant-total">Planned Total <strong>{planned}</strong> &nbsp;&nbsp; Reached Total <strong>{reached}</strong></div></Section>
 <Section n="06" title="Objectives & Activity Delivered" description="Describe what the activity intended to achieve and what was delivered."><Text label="Objectives" name="objectives" form={form} setForm={set} className="full"/><div className="grid"><Text label="What was delivered?" name="activityDelivered" form={form} setForm={set}/><Select label="Implementation status" name="implementationStatus" form={form} setForm={set} options={implementationTypes}/><Text label="Changes from the plan, if any" name="implementationChange" form={form} setForm={set}/></div></Section>
 <Section n="07" title="Results, Outcomes & Lessons" description="Capture results, participant responses, challenges and learning."><div className="grid"><Text label="Key knowledge / skills gained" name="knowledgeSkills" form={form} setForm={set}/><Text label="Key issues raised" name="keyIssues" form={form} setForm={set}/><Text label="Participant responses / feedback" name="participantFeedback" form={form} setForm={set}/><Text label="Immediate outcomes" name="immediateOutcomes" form={form} setForm={set}/><Text label="Notable achievements" name="notableAchievements" form={form} setForm={set}/><Text label="Evidence of results" name="resultsEvidence" form={form} setForm={set}/><Text label="Challenges encountered" name="challenges" form={form} setForm={set}/><Text label="How were the challenges addressed?" name="challengesAddressed" form={form} setForm={set}/><Text label="Lessons learned" name="lessonsLearned" form={form} setForm={set}/><Text label="What should be improved for future activities?" name="futureImprovements" form={form} setForm={set}/></div></Section>
 <Section n="08" title="Finance & Follow-up" description="Record financial information and actions that need to happen after the activity."><div className="table-wrap"><table className="money-table"><thead><tr><th>Financial Item</th><th>Approved Budget (ZMW)</th><th>Actual Amount Spent (ZMW)</th><th></th></tr></thead><tbody>{budgetItems.map((r,i)=><tr key={i}><td><input value={r.item} onChange={e=>setBudgetItems(b=>b.map((x,j)=>j===i?{...x,item:e.target.value}:x))}/></td><td><input type="number" value={r.approved} onChange={e=>setBudgetItems(b=>b.map((x,j)=>j===i?{...x,approved:e.target.value}:x))}/></td><td><input type="number" value={r.actual} onChange={e=>setBudgetItems(b=>b.map((x,j)=>j===i?{...x,actual:e.target.value}:x))}/></td><td><button type="button" className="small-btn" onClick={()=>setBudgetItems(b=>b.filter((_,j)=>j!==i))}>Remove</button></td></tr>)}</tbody></table></div><button type="button" className="small-btn" onClick={()=>setBudgetItems(b=>[...b,{item:'',approved:'',actual:''}])}>+ Add financial item</button><div className="grid" style={{marginTop:20}}><Field label="Approved Budget (Total) — ZMW" name="approvedBudget" form={{...form,approvedBudget:totals.approved.toFixed(2)}} setForm={()=>{}} readOnly/><Field label="Actual Amount Spent (Total) — ZMW" name="actualSpent" form={{...form,actualSpent:totals.actual.toFixed(2)}} setForm={()=>{}} readOnly/><Select label="Budget Status" name="budgetStatus" form={{...form,budgetStatus:form.budgetStatus||selectedBudget}} setForm={set} options={budgetStatuses}/></div><div className="table-wrap" style={{marginTop:20}}><table className="money-table"><thead><tr><th>Action Required</th><th>Responsible Person</th><th>Deadline</th><th>Status</th><th></th></tr></thead><tbody>{followUps.map((r,i)=><tr key={i}><td><input value={r.action} onChange={e=>setFollowUps(b=>b.map((x,j)=>j===i?{...x,action:e.target.value}:x))}/></td><td><input value={r.responsible} onChange={e=>setFollowUps(b=>b.map((x,j)=>j===i?{...x,responsible:e.target.value}:x))}/></td><td><input type="date" value={r.deadline} onChange={e=>setFollowUps(b=>b.map((x,j)=>j===i?{...x,deadline:e.target.value}:x))}/></td><td><select value={r.status} onChange={e=>setFollowUps(b=>b.map((x,j)=>j===i?{...x,status:e.target.value}:x))}><option>Pending</option><option>In Progress</option><option>Complete</option><option>Cancelled</option></select></td><td><button type="button" className="small-btn" onClick={()=>setFollowUps(b=>b.filter((_,j)=>j!==i))}>Remove</button></td></tr>)}</tbody></table></div><button type="button" className="small-btn" onClick={()=>setFollowUps(b=>[...b,{action:'',responsible:'',deadline:'',status:'Pending'}])}>+ Add action</button></Section>
 <Section n="09" title="Evidence & Overall Assessment" description="Upload all supporting evidence here, including attendance registers. Then provide safeguarding status and an overall assessment."><div className="options">{evidenceTypes.map(x=><label className="option" key={x}><input type="checkbox" checked={evidence.includes(x)} onChange={e=>setEvidence(e.target.checked?[...evidence,x]:evidence.filter(v=>v!==x))}/>{x}</label>)}</div><div style={{marginTop:20}}><input ref={fileRef} type="file" multiple hidden onChange={e=>{setFiles(p=>[...p,...Array.from(e.target.files||[])]);e.target.value=''}}/><button type="button" className="small-btn" onClick={()=>fileRef.current?.click()}>+ Add Document</button>{files.length?<div className="document-list" style={{marginTop:14}}><div className="document-list-title">Supporting Documents ({files.length})</div>{files.map((f,i)=><div className="document-item" key={`${f.name}-${i}`}><div className="document-meta"><strong>{f.name}</strong><span>{f.type||'File'} · {(f.size/1024/1024).toFixed(2)} MB</span></div><button type="button" className="small-btn" onClick={()=>setFiles(p=>p.filter((_,j)=>j!==i))}>Remove</button></div>)}</div>:<div className="hint" style={{marginTop:10}}>No documents added yet.</div>}</div><div className="grid" style={{marginTop:20}}><Select label="Safeguarding status" name="safeguardingStatus" form={form} setForm={set} options={safeguardingTypes}/><Select label="How would you rate the activity?" name="overallAssessment" form={form} setForm={set} options={assessmentTypes}/><Text label="Brief explanation" name="assessmentExplanation" form={form} setForm={set} className="full"/></div><div className="notice">Do not enter names, case details, allegations, medical information or other sensitive personal information here. Use the appropriate VSI safeguarding reporting procedure for formal cases.</div><label className="option" style={{marginTop:20}}><input type="checkbox" checked={form.declaration} onChange={e=>set({declaration:e.target.checked})}/><span>I confirm that the information provided is accurate to the best of my knowledge.</span></label></Section>
 {error&&<div className="error">{error}</div>}<div className="actions"><button className="submit" type="submit" disabled={saving}>{saving?'Uploading evidence & submitting…':'Submit Activity Report →'}</button></div>
 </form></div></main>;
}
