'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import styles from './FinanceIntelligenceStyled.module.css';

const NAV=[['Dashboard','/admin'],['Activity Reports','/admin/reports'],['Pending Review','/admin/reports?status=PENDING_REVIEW'],['Approved Reports','/admin/reports?status=APPROVED'],['Finance Intelligence','/admin/finance'],['MEAL Intelligence','/admin/meal'],['Learning & Follow-up','/admin/learning']];
const COLORS=['#094074','#3C6997','#FFC300','#FFD60A','#5B8DB8','#0B5A87'];
const num=v=>Number(v??0)||0;
const money=v=>`ZMW ${num(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const first=(o,keys)=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!=='');

function Icon({type}){const p={width:20,height:20,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round',strokeLinejoin:'round'};if(type==='people')return <svg {...p}><path d="M16 20v-1.5a3.5 3.5 0 0 0-3.5-3.5h-5A3.5 3.5 0 0 0 4 18.5V20"/><circle cx="10" cy="8" r="3"/><path d="M16 11a3 3 0 0 0 0-6M20 20v-1.2a3.4 3.4 0 0 0-2.6-3.3"/></svg>;if(type==='wallet')return <svg {...p}><path d="M3 8a3 3 0 0 1 3-3h14v14H6a3 3 0 0 1-3-3Z"/><path d="M3 8h17"/><path d="M16 12h4v4h-4a2 2 0 1 1 0-4Z"/></svg>;if(type==='spend')return <svg {...p}><path d="M12 3v18"/><path d="M17 7.5c0-1.9-2.1-3.5-5-3.5S7 5.1 7 7.2 8.7 10.5 12 11c3.3.5 5 1.8 5 4s-2.1 4-5 4-5-1.6-5-3.5"/></svg>;return <svg {...p}><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h10M7 12h10M7 16h6"/></svg>}

function Sidebar(){return <aside className={styles.sidebar}><div className={styles.brand}><div className={styles.logo}><img src="/vsi-logo-white.png" alt="Visionary Students Initiative"/></div><div><strong>VSI IMS</strong><small>ADMINISTRATION</small></div></div><div className={styles.sideLabel}>WORKSPACE</div><nav>{NAV.slice(0,4).map(([l,h])=><Link key={l} href={h}><span className={styles.dot}/>{l}</Link>)}</nav><div className={`${styles.sideLabel} ${styles.intelLabel}`}>INTELLIGENCE</div><nav>{NAV.slice(4).map(([l,h])=><Link key={l} href={h} className={l==='Finance Intelligence'?styles.active:''}><span className={`${styles.dot} ${styles.intelDot}`}/>{l}</Link>)}</nav><div className={styles.sideNote}>Finance intelligence is derived from approved activity reports.</div></aside>}

function ActivityCard({r,onClick}){const budget=num(first(r,['approved_budget','approvedBudget']));const spent=num(first(r,['actual_spent','actualSpent']));const balance=budget-spent;const reach=num(first(r,['reached_participant_total','reachedParticipantTotal','participant_total']));const util=budget?Math.round(spent/budget*100):0;const status=balance<0?'Overspent':balance>0?'Underspent':'Within Budget';return <button className={styles.activityRow} onClick={onClick} type="button"><div className={styles.activityIcon}><Icon type="activity"/></div><div className={styles.activityTitle}><span>ACTIVITY</span><h3>{r.activity_title||'Untitled activity'}</h3><p>{r.programme||'Unspecified'}{r.project?` · ${r.project}`:''}</p></div><div className={`${styles.status} ${balance<0?styles.danger:balance>0?styles.warn:styles.ok}`}>{status}</div><div className={styles.activityMoney}><div><span>APPROVED</span><b>{money(budget)}</b></div><div><span>SPENT</span><b>{money(spent)}</b></div><div><span>BALANCE</span><b className={balance<0?styles.dangerText:''}>{money(Math.abs(balance))}</b></div></div><div className={styles.activityProgress}><div className={styles.progressHead}><span>Budget utilisation</span><b>{util}%</b></div><div className={styles.progress}><i style={{width:`${Math.min(100,Math.max(0,util))}%`}}/></div><small><Icon type="people"/>{reach.toLocaleString()} reached</small></div><div className={styles.detailLink}>View financial detail <span>→</span></div></button>}

export default function FinanceIntelligenceFinal(){const[details,setDetails]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[programme,setProgramme]=useState('All'),[funding,setFunding]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null);
useEffect(()=>{let dead=false;(async()=>{try{const res=await fetch('/api/admin/activity-reports',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load finance intelligence.');const approved=(data.reports||[]).filter(r=>r.review_status==='APPROVED');const full=await Promise.all(approved.map(async r=>{try{const rr=await fetch(`/api/admin/activity-reports/${encodeURIComponent(r.reference)}`,{cache:'no-store'});const dd=await rr.json();return dd.report||r}catch{return r}}));if(!dead)setDetails(full)}catch(e){if(!dead)setError(e.message)}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[]);
const rows=useMemo(()=>details.filter(r=>{if(programme!=='All'&&(r.programme||'Unspecified')!==programme)return false;if(funding!=='All'&&(r.funding_source||'Unspecified')!==funding)return false;const q=query.trim().toLowerCase();return !q||[r.reference,r.activity_title,r.programme,r.project,r.directorate,r.donor_name,r.grant_title,r.grant_reference].filter(Boolean).join(' ').toLowerCase().includes(q)}),[details,programme,funding,query]);
const programmes=useMemo(()=>['All',...new Set(details.map(r=>r.programme||'Unspecified'))],[details]);const fundings=useMemo(()=>['All',...new Set(details.map(r=>r.funding_source||'Unspecified'))],[details]);const totals=useMemo(()=>rows.reduce((a,r)=>{a.budget+=num(first(r,['approved_budget','approvedBudget']));a.spent+=num(first(r,['actual_spent','actualSpent']));a.reach+=num(first(r,['reached_participant_total','reachedParticipantTotal','participant_total']));return a},{budget:0,spent:0,reach:0}),[rows]);
const balance=totals.budget-totals.spent,util=totals.budget?Math.round(totals.spent/totals.budget*100):0,cost=totals.reach?totals.spent/totals.reach:0;const breakdown=useMemo(()=>{const map=new Map();rows.forEach(r=>{const name=r.programme||'Unspecified';const x=map.get(name)||{name,spent:0};x.spent+=num(first(r,['actual_spent','actualSpent']));map.set(name,x)});const total=[...map.values()].reduce((s,x)=>s+x.spent,0);return[...map.values()].sort((a,b)=>b.spent-a.spent).map((x,i)=>({...x,pct:total?Math.round(x.spent/total*100):0,color:COLORS[i%COLORS.length]}))},[rows]);
const donorBreakdown=useMemo(()=>{const map=new Map();rows.forEach(r=>{const donor=r.donor_name||'Unspecified donor';const x=map.get(donor)||{name:donor,projects:new Set(),activities:0,budget:0,spent:0};if(r.project)x.projects.add(r.project);x.activities+=1;x.budget+=num(first(r,['approved_budget','approvedBudget']));x.spent+=num(first(r,['actual_spent','actualSpent']));map.set(donor,x)});return[...map.values()].sort((a,b)=>b.budget-a.budget).map(x=>({...x,projects:[...x.projects],util:x.budget?Math.round(x.spent/x.budget*100):0}))},[rows]);
const gradient=useMemo(()=>{let start=0;return breakdown.length?breakdown.map(x=>{const end=start+x.pct*3.6;const part=`${x.color} ${start}deg ${end}deg`;start=end;return part}).join(', '):'#dce5ec 0deg 360deg'},[breakdown]);const selectedValues=selected?(()=>{const b=num(first(selected,['approved_budget','approvedBudget'])),s=num(first(selected,['actual_spent','actualSpent'])),reach=num(first(selected,['reached_participant_total','reachedParticipantTotal','participant_total']));return{b,s,balance:b-s,reach,cost:reach?s/reach:0,util:b?Math.round(s/b*100):0}})():null;
return <div className={styles.app}><Sidebar/><main className={styles.main}><header className={styles.header}><div><div className={styles.kicker}>VSI ADMINISTRATION · FINANCE INTELLIGENCE</div><h1>Finance Intelligence</h1><p>Approved financial performance across VSI activity reports.</p></div><div className={styles.headerRight}><div className={styles.vsiBrand}><img src="/vsi-logo-white.png" alt="VSI"/><div><strong>VSI</strong><small>VISIONARY STUDENTS INITIATIVE</small></div></div><Link className={styles.action} href="/admin/reports?status=APPROVED">Approved Reports <span>→</span></Link></div></header>
<section className={styles.note}><span className={styles.info}>i</span><div><strong>Approved data only</strong><p>Financial intelligence reflects reports that have completed administrative approval.</p></div></section>
<section className={styles.creditGrid}><div className={`${styles.credit} ${styles.blue}`}><div className={styles.shape}/><span>APPROVED BUDGET</span><strong>{money(totals.budget)}</strong><small>Authorised activity budget</small><div className={styles.creditFoot}><span><Icon type="wallet"/>VSI</span><span>{rows.length} activities</span></div></div><div className={`${styles.credit} ${styles.navy}`}><div className={styles.shape}/><span>ACTUAL SPEND</span><strong>{money(totals.spent)}</strong><small>Reported expenditure</small><div className={styles.creditFoot}><span><Icon type="spend"/>APPROVED</span><span>{util}% utilised</span></div></div><div className={`${styles.credit} ${styles.gold}`}><div className={styles.shape}/><span>BALANCE</span><strong>{money(Math.abs(balance))}</strong><small>{balance<0?'Above approved budget':'Remaining approved budget'}</small><div className={styles.creditFoot}><span><Icon type="balance"/>POSITION</span><span>{balance<0?'OVERSPENT':balance>0?'AVAILABLE':'FULLY UTILISED'}</span></div></div></section>
<section className={styles.miniGrid}><div><Icon type="activity"/><div><span>APPROVED ACTIVITIES</span><b>{rows.length}</b></div></div><div><Icon type="people"/><div><span>PARTICIPANTS REACHED</span><b>{totals.reach.toLocaleString()}</b></div></div><div><Icon type="spend"/><div><span>COST / PARTICIPANT</span><b>{totals.reach?money(cost):'—'}</b></div></div></section>
<section className={styles.twoCol}><div className={styles.panel}><div className={styles.panelHead}><div><div className={styles.sectionKicker}>ACTIVITY DETAILS</div><h2>Approved activity expenditure</h2><p>Click an activity to open its financial detail.</p></div><span className={styles.count}>{rows.length}</span></div><div className={styles.filters}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search activity, programme, project, donor or grant…"/><select value={programme} onChange={e=>setProgramme(e.target.value)}>{programmes.map(x=><option key={x}>{x}</option>)}</select><select value={funding} onChange={e=>setFunding(e.target.value)}>{fundings.map(x=><option key={x}>{x}</option>)}</select></div>{loading?<div className={styles.empty}>Loading finance intelligence…</div>:error?<div className={styles.error}>{error}</div>:<div className={styles.activityList}>{rows.map(r=><ActivityCard key={r.reference} r={r} onClick={()=>setSelected(r)}/>)}{!rows.length&&<div className={styles.empty}>No approved finance records match this view.</div>}</div>}</div>
<div className={`${styles.panel} ${styles.attribution}`}><div className={styles.panelHead}><div><div className={styles.sectionKicker}>PROGRAMME & GRANT ATTRIBUTION</div><h2>Financial footprint</h2><p>Approved expenditure by programme.</p></div></div><div className={styles.donutWrap}><div className={styles.donut} style={{background:`conic-gradient(${gradient})`}}><div className={styles.donutHole}><strong>{util}%</strong><span>utilised</span></div></div></div><div className={styles.legend}>{breakdown.map(x=><div className={styles.legendItem} key={x.name}><span className={styles.legendDot} style={{background:x.color}}/><div><b>{x.name}</b><small>{money(x.spent)}</small></div><strong>{x.pct}%</strong></div>)}</div></div></section>
<section className={`${styles.panel} ${styles.util}`}><div className={styles.panelHead}><div><div className={styles.sectionKicker}>DONOR BUDGET UTILISATION</div><h2>Donor-supported activity portfolio</h2><p>Projects and activities supported by each donor.</p></div><strong className={styles.utilNumber}>{donorBreakdown.length}</strong></div><div style={{display:'grid',gap:'10px',marginTop:'14px'}}>{donorBreakdown.map(d=><div key={d.name} style={{border:'1px solid #dfe5ea',borderRadius:'10px',padding:'13px 15px',background:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',gap:'12px'}}><strong style={{color:'#003566',fontSize:'14px'}}>{d.name}</strong><b style={{color:'#003566',fontSize:'13px'}}>{d.util}% utilised</b></div><div style={{color:'#65717d',fontSize:'11px',marginTop:'5px',lineHeight:1.45}}>{d.projects.length?d.projects.join(' · '):'No project recorded'} · {d.activities} {d.activities===1?'activity':'activities'}</div><div style={{display:'flex',justifyContent:'space-between',gap:'12px',marginTop:'9px',fontSize:'10px',color:'#52606d'}}><span>Approved <b style={{color:'#003566'}}>{money(d.budget)}</b></span><span>Spent <b style={{color:'#003566'}}>{money(d.spent)}</b></span><span>Balance <b style={{color:'#003566'}}>{money(d.budget-d.spent)}</b></span></div><div className={styles.bigProgress} style={{marginTop:'9px'}}><i style={{width:`${Math.min(100,Math.max(0,d.util))}%`}}/></div></div>)}{!donorBreakdown.length&&<div className={styles.empty}>No approved donor information is available.</div>}</div></section>
{selected&&<div className={styles.backdrop} role="presentation" onClick={()=>setSelected(null)}><div className={styles.modal} role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className={styles.close} type="button" onClick={()=>setSelected(null)} aria-label="Close">×</button><div className={styles.sectionKicker}>ACTIVITY FINANCIAL DETAIL</div><h2>{selected.activity_title||'Untitled activity'}</h2><p>{selected.programme||'Unspecified'}{selected.project?` · ${selected.project}`:''}</p><div className={styles.detailGrid}><div><span>APPROVED</span><b>{money(selectedValues.b)}</b></div><div><span>SPENT</span><b>{money(selectedValues.s)}</b></div><div><span>BALANCE</span><b>{money(Math.abs(selectedValues.balance))}</b></div><div><span>UTILISATION</span><b>{selectedValues.util}%</b></div></div><div className={styles.modalStatus}><strong>{selectedValues.balance<0?'Overspent':selectedValues.balance>0?'Underspent':'Within Budget'}</strong><span>{selectedValues.reach.toLocaleString()} participants</span></div><div className={styles.modalMeta}><div><span>Grant</span><b>{selected.grant_title||'—'}</b></div><div><span>Reference</span><b>{selected.grant_reference||selected.reference||'—'}</b></div><div><span>Cost / participant</span><b>{selectedValues.reach?money(selectedValues.cost):'—'}</b></div></div><Link className={styles.modalLink} href={`/admin/reports?search=${encodeURIComponent(selected.reference||selected.activity_title||'')}`}>Open report register →</Link></div></div>}
</main></div>;
}
