'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

const NAV=[['Dashboard','/admin'],['Activity Reports','/admin/reports'],['Pending Review','/admin/reports?status=PENDING_REVIEW'],['Approved Reports','/admin/reports?status=APPROVED'],['Finance Intelligence','/admin/finance'],['MEAL Intelligence','/admin/meal'],['Learning & Follow-up','/admin/learning']];
const first=(o,keys,fallback='')=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!=='')??fallback;
const text=v=>v===null||v===undefined||v===''?'Not recorded':String(v);
const list=v=>{if(!v)return[];if(Array.isArray(v))return v;try{const x=typeof v==='string'?JSON.parse(v):v;return Array.isArray(x)?x:[]}catch{return[]}};
const dateOnly=v=>v?new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';
const daysUntil=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:Math.ceil((d.getTime()-Date.now())/86400000)};

function Sidebar(){return <aside className="admin-sidebar"><div className="side-brand"><div className="side-logo-wrap"><img src="/vsi-logo-white.png" alt="Visionary Students Initiative"/></div><div className="side-brand-copy"><strong>VSI IMS</strong><small>ADMINISTRATION</small></div></div><div className="side-label">WORKSPACE</div><nav>{NAV.slice(0,4).map(([label,href])=><Link key={label} href={href}><span className="nav-dot"/>{label}</Link>)}</nav><div className="side-label intelligence">INTELLIGENCE</div><nav>{NAV.slice(4).map(([label,href])=><Link key={label} href={href} className={label==='Learning & Follow-up'?'active':''}><span className="nav-dot intel-dot"/>{label}</Link>)}</nav><div className="side-note">Institutional learning turns completed activity reporting into practical follow-up and programme improvement.</div><Link className="back-report" href="/activity-report">Open Activity Report ↗</Link></aside>}

function actionsFor(report){return list(first(report,['follow_up_actions','followUpActions'],[])).map((x,i)=>({id:`${report.reference}-${i}`,action:x?.action||x?.description||x?.task||'',responsible:x?.responsible||x?.assignee||x?.assignedTo||'',deadline:x?.deadline||x?.dueDate||x?.due_date||'',status:x?.status||'Pending',reference:report.reference,activity:first(report,['activity_title','activityTitle'],'Activity')})).filter(x=>x.action||x.responsible||x.deadline)}

export default function Phase5Dashboard(){
 const [reports,setReports]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let dead=false;(async()=>{try{const r=await fetch('/api/admin/activity-reports',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load learning intelligence.');const approved=(d.reports||[]).filter(x=>x.review_status==='APPROVED');const full=await Promise.all(approved.map(async x=>{try{const rr=await fetch(`/api/admin/activity-reports/${encodeURIComponent(x.reference)}`,{cache:'no-store'}),dd=await rr.json();return dd.report||x}catch{return x}}));if(!dead)setReports(full)}catch(e){if(!dead)setError(e.message)}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[]);
 const actions=useMemo(()=>reports.flatMap(actionsFor),[reports]);
 const stats=useMemo(()=>({pending:actions.filter(a=>String(a.status).toLowerCase()==='pending').length,progress:actions.filter(a=>/in.?progress/i.test(String(a.status))).length,complete:actions.filter(a=>/complete/i.test(String(a.status))).length,overdue:actions.filter(a=>{const d=daysUntil(a.deadline);return d!==null&&d<0&&!/complete/i.test(String(a.status))}).length}),[actions]);
 const learning=useMemo(()=>({challenges:reports.filter(r=>first(r,['challenges'])).length,addressed:reports.filter(r=>first(r,['challenges_addressed','challengesAddressed'])).length,lessons:reports.filter(r=>first(r,['lessons_learned','lessonsLearned'])).length,improvements:reports.filter(r=>first(r,['future_improvements','futureImprovements'])).length}),[reports]);
 const programmeLearning=useMemo(()=>{const m=new Map();reports.forEach(r=>{const name=first(r,['programme','programme_name','programmeName'],'Unspecified');const x=m.get(name)||{name,reports:0,challenges:0,lessons:0,improvements:0};x.reports++;if(first(r,['challenges']))x.challenges++;if(first(r,['lessons_learned','lessonsLearned']))x.lessons++;if(first(r,['future_improvements','futureImprovements']))x.improvements++;m.set(name,x)});return[...m.values()]},[reports]);
 const coverage=v=>reports.length?Math.round(v/reports.length*100):0;
 const lessonReports=reports.filter(r=>first(r,['lessons_learned','lessonsLearned']));
 const improvementReports=reports.filter(r=>first(r,['future_improvements','futureImprovements']));
 return <div className="admin-app"><Sidebar/><main className="admin-main">
   <header className="admin-header"><div><div className="admin-kicker">VSI ADMINISTRATION · PHASE 5</div><h1>Learning &amp; Follow-up Intelligence</h1><p>Turn approved activity reports into accountable follow-up, institutional learning and practical programme improvement.</p></div><Link href="/admin/reports?status=APPROVED" className="header-action">Approved Reports →</Link></header>
   {loading&&<div className="admin-notice">Loading institutional learning intelligence…</div>}
   {error&&<div className="admin-error">{error}</div>}
   {!loading&&!error&&<>
    <section className="stat-grid p5-stat-grid">
      <Link className="stat-link" href="/admin/reports?status=APPROVED"><div className="stat-card navy"><span>APPROVED REPORTS</span><strong>{reports.length}</strong><small>Trusted learning dataset</small></div></Link>
      <Link className="stat-link" href="#follow-up"><div className="stat-card yellow"><span>FOLLOW-UP ACTIONS</span><strong>{actions.length}</strong><small>{stats.overdue} overdue</small></div></Link>
      <div className="stat-card green"><span>ACTIONS COMPLETE</span><strong>{stats.complete}</strong><small>Closed follow-up items</small></div>
      <div className="stat-card"><span>LESSONS CAPTURED</span><strong>{learning.lessons}</strong><small>Reports with lessons learned</small></div>
    </section>

    <section className="dashboard-grid">
      <article id="follow-up" className="dash-panel wide hero-panel"><div className="panel-head"><div><span>SECTION 10 · FOLLOW-UP ACTIONS</span><h2>Operational follow-up tracker</h2></div><span className="p5-count">{actions.length} actions</span></div>
       <div className="metric-grid p5-action-grid"><div><small>Pending</small><strong>{stats.pending}</strong><span>Open actions</span></div><div><small>In Progress</small><strong>{stats.progress}</strong><span>Being addressed</span></div><div><small>Complete</small><strong>{stats.complete}</strong><span>Closed items</span></div><div><small>Overdue</small><strong className={stats.overdue?'p5-danger':''}>{stats.overdue}</strong><span>Past deadline</span></div></div>
       {actions.length?<div className="table-wrap p5-table-wrap"><table className="p5-table"><colgroup><col style={{width:'25%'}}/><col style={{width:'35%'}}/><col style={{width:'16%'}}/><col style={{width:'12%'}}/><col style={{width:'12%'}}/></colgroup><thead><tr><th>Activity</th><th>Follow-up action</th><th>Responsible</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{actions.slice(0,30).map(a=>{const d=daysUntil(a.deadline),overdue=d!==null&&d<0&&!/complete/i.test(String(a.status)),sc=String(a.status).toLowerCase().replace(/\s+/g,'-');return <tr key={a.id}><td><strong>{a.activity}</strong><small>{a.reference}</small></td><td>{text(a.action)}</td><td>{text(a.responsible)}</td><td className={overdue?'p5-danger':''}>{dateOnly(a.deadline)}{overdue&&<small>Overdue</small>}</td><td><span className={`status-pill ${sc}`}>{a.status}</span></td></tr>})}</tbody></table></div>:<div className="empty">No follow-up actions have been recorded in approved reports yet.</div>}
      </article>

      <article className="dash-panel"><div className="panel-head"><div><span>SECTION 08 · RESULTS &amp; LESSONS</span><h2>Institutional learning coverage</h2></div></div><div className="p5-bars">{[['Challenges captured',learning.challenges],['Challenges addressed',learning.addressed],['Lessons learned',learning.lessons],['Future improvements',learning.improvements]].map(([label,value])=><div key={label}><div><span>{label}</span><strong>{value}</strong></div><div className="p5-bar"><i style={{width:`${coverage(value)}%`}}/></div></div>)}</div></article>

      <article className="dash-panel"><div className="panel-head"><div><span>LEARNING SIGNALS</span><h2>Recent lessons learned</h2></div></div>{lessonReports.length?<div className="p5-feed">{lessonReports.slice(0,6).map(r=><div className="p5-feed-row" key={r.reference}><strong>{first(r,['activity_title','activityTitle'],'Activity')}</strong><p>{text(first(r,['lessons_learned','lessonsLearned']))}</p><small>{first(r,['programme','programme_name'],'Unspecified')} · {r.reference}</small></div>)}</div>:<div className="empty">Lessons learned will appear here as approved reports capture Section 08 learning.</div>}</article>

      <article className="dash-panel wide"><div className="panel-head"><div><span>ADAPTIVE PROGRAMMING</span><h2>Future improvements recorded by officers</h2></div></div>{improvementReports.length?<div className="p5-improvement-grid">{improvementReports.slice(0,8).map(r=><div className="p5-improvement" key={r.reference}><strong>{first(r,['activity_title','activityTitle'],'Activity')}</strong><p>{text(first(r,['future_improvements','futureImprovements']))}</p><small>Programme: {first(r,['programme','programme_name'],'Unspecified')}</small></div>)}</div>:<div className="empty">Future improvements will appear here after officers record Section 08 recommendations.</div>}</article>

      <article className="dash-panel wide"><div className="panel-head"><div><span>PROGRAMME LEARNING PROFILE</span><h2>Where learning is being captured</h2></div></div>{programmeLearning.length?<div className="programme-list">{programmeLearning.map(p=><div className="programme-row" key={p.name}><div><strong>{p.name}</strong><small>{p.reports} approved report{p.reports===1?'':'s'}</small></div><div className="p5-programme-metrics"><span>Challenges <b>{p.challenges}</b></span><span>Lessons <b>{p.lessons}</b></span><span>Improvements <b>{p.improvements}</b></span></div></div>)}</div>:<div className="empty">Programme learning profiles will populate as approved reports are available.</div>}</article>

      <article className="dash-panel wide"><div className="panel-head"><div><span>MANAGEMENT INTERPRETATION</span><h2>Learning-to-action signal</h2></div></div><div className="p5-callout"><strong>{stats.overdue?`${stats.overdue} follow-up ${stats.overdue===1?'action is':'actions are'} overdue.`:'No overdue follow-up actions.'}</strong><p>{learning.lessons?`${learning.lessons} approved report${learning.lessons===1?'':'s'} contain lessons learned, providing an evidence base for future programme decisions.`:'Institutional learning will strengthen as officers record lessons learned and future improvements in Section 08.'}</p><Link href="/admin/reports?status=APPROVED">Open approved reports →</Link></div></article>
    </section>
   </>}
 </main><style jsx>{`
.p5-stat-grid{margin-bottom:16px}.p5-count{color:#65717d;font-size:10px;white-space:nowrap}.p5-action-grid{margin-bottom:16px}.p5-table-wrap{width:100%;overflow-x:auto}.p5-table{width:100%;min-width:900px;border-collapse:collapse;table-layout:fixed}.p5-table th{padding:10px;text-align:left;background:#f4f7fa;color:#52606d;font-size:9px;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap}.p5-table td{padding:12px 10px;border-top:1px solid #e7edf1;color:#36434f;font-size:11px;line-height:1.45;vertical-align:top;overflow-wrap:anywhere}.p5-table td strong,.p5-table td small{display:block}.p5-table td strong{color:#003566}.p5-table td small{margin-top:3px;color:#65717d;font-size:9px}.p5-danger{color:#b42318!important}.status-pill{display:inline-flex;align-items:center;justify-content:center;padding:5px 9px;border-radius:999px;background:#fff4cc;color:#8a5a00;font-size:9px;font-weight:900;white-space:nowrap}.status-pill.in-progress{background:#e0efff;color:#094074}.status-pill.complete{background:#dcfce7;color:#15803d}.p5-bars{display:flex;flex-direction:column;gap:15px}.p5-bars>div>div:first-child{display:flex;justify-content:space-between;gap:10px}.p5-bars span{color:#52606d;font-size:10px}.p5-bars strong{color:#003566;font-size:12px}.p5-bar{height:7px;margin-top:6px;background:#edf1f4;border-radius:6px;overflow:hidden}.p5-bar i{display:block;height:100%;background:#ffc300;border-radius:6px}.p5-feed{display:flex;flex-direction:column}.p5-feed-row{padding:12px 0;border-bottom:1px solid #e7edf1}.p5-feed-row:last-child{border-bottom:0}.p5-feed-row strong{display:block;color:#003566;font-size:11px}.p5-feed-row p{margin:5px 0;color:#36434f;font-size:11px;line-height:1.55;overflow-wrap:anywhere}.p5-feed-row small,.p5-improvement small{color:#65717d;font-size:9px}.p5-improvement-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.p5-improvement{min-width:0;padding:14px;background:#f6f9fb;border-radius:9px}.p5-improvement strong{display:block;color:#003566;font-size:11px}.p5-improvement p{margin:6px 0;color:#36434f;font-size:11px;line-height:1.55;overflow-wrap:anywhere}.p5-programme-metrics{display:flex;gap:16px;flex-wrap:wrap;justify-content:flex-end}.p5-programme-metrics span{color:#65717d;font-size:10px;white-space:nowrap}.p5-programme-metrics b{color:#003566;margin-left:4px}.p5-callout{padding:18px;border-left:4px solid #ffc300;background:#f6f9fb;border-radius:0 10px 10px 0}.p5-callout strong{display:block;color:#003566;font-size:16px}.p5-callout p{margin:7px 0 12px;color:#65717d;font-size:11px;line-height:1.55}.p5-callout a{color:#094074;text-decoration:none;font-size:11px;font-weight:900}@media(max-width:900px){.p5-improvement-grid{grid-template-columns:1fr}}@media(max-width:760px){.p5-programme-metrics{justify-content:flex-start}.p5-action-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:420px){.p5-action-grid{grid-template-columns:1fr!important}}
`}</style></div>;
}
