import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { neon } from '@neondatabase/serverless';
import { isAdminSession } from '../../../api/admin/login/route';
import ReviewActions from './ReviewActions';

export const dynamic = 'force-dynamic';
function Field({ label, value }) { return <div style={{ padding: '12px 14px', border: '1px solid var(--line)', borderRadius: 10, background: '#fff' }}><div className="kicker" style={{ marginBottom: 5 }}>{label}</div><div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.55 }}>{value === null || value === undefined || value === '' ? '—' : String(value)}</div></div>; }
function parseJson(value, fallback = []) { if (Array.isArray(value)) return value; if (!value) return fallback; try { return typeof value === 'string' ? JSON.parse(value) : value; } catch { return fallback; } }
function ParticipantGrid({ title, report, prefix }) { const rows=[['Male','male'],['Female','female'],['PWD Male','pwd_male'],['PWD Female','pwd_female']]; const ages=[['Children','children'],['Youth','youth'],['Adult','adult']]; return <div style={{ marginTop: 18 }}><h3>{title}</h3><div className="table-wrap"><table className="money-table"><thead><tr><th>Category</th>{ages.map(([x])=><th key={x}>{x}</th>)}<th>Total</th></tr></thead><tbody>{rows.map(([label,key])=>{const vals=ages.map(([,age])=>Number(report[`${prefix}_${key}_${age}`])||0);return <tr key={key}><td><strong>{label}</strong></td>{vals.map((v,i)=><td key={i}>{v}</td>)}<td>{vals.reduce((a,b)=>a+b,0)}</td></tr>})}</tbody></table></div></div>; }

export default async function AdminReportDetail({ params }) {
  const token=(await cookies()).get('vsi_admin_session')?.value;
  if(!isAdminSession(token)) redirect('/admin/login');
  const { reference }=await params; const sql=neon(process.env.DATABASE_URL);
  await sql`ALTER TABLE activity_reports ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'PENDING_REVIEW'`;
  await sql`ALTER TABLE activity_reports ADD COLUMN IF NOT EXISTS reviewed_by TEXT`;
  await sql`ALTER TABLE activity_reports ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ`;
  await sql`ALTER TABLE activity_reports ADD COLUMN IF NOT EXISTS review_comment TEXT`;
  const rows=await sql`SELECT * FROM activity_reports WHERE reference = ${reference} LIMIT 1`;
  if(!rows.length) return <main className="page"><div className="shell"><div className="error">Report not found.</div><Link href="/admin/reports">← Back to Reports Inbox</Link></div></main>;
  const report=rows[0], attachments=parseJson(report.attachments), budgetItems=parseJson(report.budget_items), followUps=parseJson(report.follow_up_actions), evidence=parseJson(report.evidence_available);
  const sections=[
    ['01','Activity Identification','Approved activity and core identification details.',<div className="grid"><Field label="Activity Code" value={report.activity_code}/><Field label="Activity Name" value={report.activity_title}/><Field label="Programme" value={report.programme}/><Field label="Project" value={report.project}/><Field label="Directorate" value={report.directorate}/><Field label="UN SDGs Alignment" value={report.activity_sdgs}/><Field label="AU Agenda 2063 Alignment" value={report.activity_au_agenda2063}/><Field label="Activity Date" value={report.activity_date ? new Date(report.activity_date).toLocaleDateString() : ''}/><Field label="Start Time" value={report.start_time}/><Field label="End Time" value={report.end_time}/><Field label="Activity Type" value={report.activity_type === 'Other' ? report.activity_type_other : report.activity_type}/><Field label="Brief Description" value={report.activity_description}/></div>],
    ['02','Activity Location','Where the activity took place.',<div className="grid"><Field label="Province" value={report.province}/><Field label="District" value={report.district}/><Field label="Constituency" value={report.constituency}/><Field label="Ward / Community" value={report.ward_community}/><Field label="Specific Venue / Location" value={report.venue}/></div>],
    ['03','Reporting Officer','Reporting officer and supervisor information.',<div className="grid"><Field label="Full Name" value={report.reporter_full_name}/><Field label="Position / Role" value={report.reporter_position}/><Field label="Phone Number" value={report.reporter_phone}/><Field label="Email Address" value={report.reporter_email}/><Field label="Supervisor's Full Name" value={report.supervisor_full_name}/><Field label="Position / Role" value={report.supervisor_position}/><Field label="Phone Number" value={report.supervisor_phone}/><Field label="Email Address" value={report.supervisor_email}/></div>],
    ['04','Funding & Partners','Funding, facilitators and partner organisations.',<div className="grid"><Field label="Funding Source" value={report.funding_source}/><Field label="Donor Name" value={report.donor_name}/><Field label="Project / Grant Title" value={report.grant_title}/><Field label="Grant / Project Reference" value={report.grant_reference}/><Field label="Grant Manager / Donor Contact" value={report.grant_manager}/><Field label="Grant Manager Phone" value={report.grant_phone}/><Field label="Grant Manager Email" value={report.grant_email}/><Field label="Lead Facilitator" value={report.lead_facilitator}/><Field label="Other VSI Staff / Volunteers Involved" value={report.other_staff_volunteers}/><Field label="Partner Organisation(s)" value={report.partner_organisations}/><Field label="Partner Contact Person" value={report.partner_contact}/></div>],
    ['05','Participants & Attendance','Planned and reached participant figures, including PWD breakdown.',<><ParticipantGrid title="Planned Participants" report={report} prefix="planned"/><ParticipantGrid title="Reached Participants" report={report} prefix="reached"/><div className="grid" style={{ marginTop:18 }}><Field label="Planned Total" value={report.planned_participant_total}/><Field label="Reached Total" value={report.reached_participant_total}/><Field label="Performance" value={report.participant_performance}/><Field label="Achievement" value={report.participant_performance_percent ? `${report.participant_performance_percent}%` : ''}/><Field label="Variance" value={(Number(report.reached_participant_total)||0)-(Number(report.planned_participant_total)||0)}/><Field label="Performance Justification" value={report.participant_performance_justification}/></div></>],
    ['06','Activity Objectives','What the activity was intended to achieve.',<div className="grid"><Field label="Objectives" value={report.objectives}/></div>],
    ['07','Activity Delivered','What actually happened and how it was implemented.',<div className="grid"><Field label="What was delivered?" value={report.activity_delivered}/><Field label="Implementation Status" value={report.implementation_status}/><Field label="Changes from the plan, if any" value={report.implementation_change}/></div>],
    ['08','Results, Outcomes & Lessons','Results, feedback, challenges and learning.',<div className="grid"><Field label="Key Knowledge / Skills Gained" value={report.knowledge_skills}/><Field label="Key Issues Raised" value={report.key_issues}/><Field label="Participant Responses / Feedback" value={report.participant_feedback}/><Field label="Immediate Outcomes" value={report.immediate_outcomes}/><Field label="Notable Achievements" value={report.notable_achievements}/><Field label="Evidence of Results" value={report.results_evidence}/><Field label="Challenges Encountered" value={report.challenges}/><Field label="How Were the Challenges Addressed?" value={report.challenges_addressed}/><Field label="Lessons Learned" value={report.lessons_learned}/><Field label="What Should Be Improved for Future Activities?" value={report.future_improvements}/></div>],
    ['09','Finance & Budget','Financial information and budget performance.',<><div className="grid"><Field label="Approved Budget (ZMW)" value={report.approved_budget}/><Field label="Actual Amount Spent (ZMW)" value={report.actual_spent}/><Field label="Balance / (Overspend)" value={(Number(report.approved_budget)||0)-(Number(report.actual_spent)||0)}/><Field label="Budget Status" value={report.budget_status}/><Field label="Overspend Cause" value={report.overspend_cause}/></div>{budgetItems.length>0&&<div style={{marginTop:18}}><h3>Budget Items</h3><div className="table-wrap"><table className="money-table"><thead><tr><th>Item</th><th>Approved</th><th>Actual</th></tr></thead><tbody>{budgetItems.map((x,i)=><tr key={i}><td>{x.item||'—'}</td><td>{x.approved||0}</td><td>{x.actual||0}</td></tr>)}</tbody></table></div></div>}</div></>],
    ['10','Follow-up Actions','Actions required after the activity.',<>{followUps.length>0?<div className="table-wrap"><table className="money-table"><thead><tr><th>Action Required</th><th>Responsible Person</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{followUps.map((x,i)=><tr key={i}><td>{x.action||'—'}</td><td>{x.responsible||'—'}</td><td>{x.deadline||'—'}</td><td>{x.status||'—'}</td></tr>)}</tbody></table></div>:<div className="vsi-document-empty">No follow-up actions recorded.</div>}</>],
    ['11','Evidence & Attachments','Supporting documents submitted with the report.',<>{evidence.length>0&&<div className="options" style={{marginBottom:18}}>{evidence.map(x=><span className="option" key={x}>{x}</span>)}</div>}{attachments.length?<div className="vsi-document-table"><div className="vsi-document-row vsi-document-head"><span>Document</span><span>Type / Size</span><span>Open</span></div>{attachments.map((file,i)=><div className="vsi-document-row" key={i}><div className="vsi-document-file"><strong>{file.name||'Unnamed document'}</strong></div><div>{file.type||'File'} · {file.size?`${(Number(file.size)/1024/1024).toFixed(2)} MB`:'Size unavailable'}</div><div>{file.url?<a href={file.url} target="_blank" rel="noreferrer" className="small-btn" style={{display:'inline-block',textDecoration:'none'}}>Open ↗</a>:'—'}</div></div>)}</div>:<div className="vsi-document-empty">No uploaded documents were attached to this report.</div>}<p className="hint" style={{marginTop:12}}>Evidence uploaded: {report.evidence_uploaded||'—'} · Photo/media consent: {report.photo_media_consent||'—'}</p></>],
    ['12','Overall Activity Assessment','Overall rating and safeguarding status.',<div className="grid"><Field label="How would you rate the activity?" value={report.overall_assessment}/><Field label="Brief Explanation" value={report.assessment_explanation}/><Field label="Safeguarding Status" value={report.safeguarding_status}/><Field label="Short Description of Concern" value={report.safeguarding_description}/><Field label="Measures Taken / Action Taken" value={report.safeguarding_measures}/></div>]
  ];
  return <main className="page"><div className="topbar"><div className="topbar-inner"><div className="brand"><img src="/vsi-logo-white.png" alt="Visionary Students Initiative" className="vsi-logo"/></div><span>ACTIVITY REPORT</span><div className="social-links"><a href="https://web.facebook.com/vsizambia" target="_blank" rel="noreferrer">f</a><a href="https://www.linkedin.com/in/visionary-students-initiative-vsi-0a447238/" target="_blank" rel="noreferrer">in</a><a href="https://www.instagram.com/vsizambia" target="_blank" rel="noreferrer">◎</a><a href="https://www.youtube.com/@vsizambia" target="_blank" rel="noreferrer">▶</a><a href="https://www.vsizambia.org" target="_blank" rel="noreferrer">↗</a></div></div></div><div className="shell"><header className="form-intro"><p><strong>VSI ADMINISTRATION · ACTIVITY REPORT REVIEW</strong><br/>Review the submitted record section by section in the same order used by the reporting officer.</p></header><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:18,flexWrap:'wrap'}}><div><p className="kicker">ACTIVITY REPORT</p><h1 style={{margin:0,color:'var(--regal-navy)'}}>{report.activity_title}</h1><p style={{color:'var(--muted)',marginBottom:0}}>{report.reference} · {report.activity_date?new Date(report.activity_date).toLocaleDateString():'—'}</p></div><Link href="/admin/reports" className="small-btn" style={{textDecoration:'none'}}>← Reports Inbox</Link></div>{sections.map(([n,title,description,content])=><section className="section" key={n}><div className="section-head"><span className="number">{n}</span><div><h2>{title}</h2><p>{description}</p></div></div><div className="section-body">{content}</div></section>)}<section className="section"><div className="section-head"><span className="number">✓</span><div><h2>Administrative Review</h2><p>Complete the workflow decision after reviewing Sections 01–12.</p></div></div><div className="section-body"><ReviewActions reference={report.reference} status={report.review_status||'PENDING_REVIEW'} comment={report.review_comment||''}/>{report.reviewed_at&&<p className="hint" style={{marginTop:14}}>Last reviewed {new Date(report.reviewed_at).toLocaleString()} by {report.reviewed_by||'Administrator'}.</p>}</div></section></div></main>;
}
