import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { neon } from '@neondatabase/serverless';
import { isAdminSession } from '../../../api/admin/login/route';

export const dynamic = 'force-dynamic';

function Field({ label, value }) {
  return <div style={{ padding: '12px 14px', border: '1px solid var(--line)', borderRadius: 10, background: '#fff' }}><div className="kicker" style={{ marginBottom: 5 }}>{label}</div><div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.55 }}>{value === null || value === undefined || value === '' ? '—' : String(value)}</div></div>;
}

function parseJson(value, fallback = []) {
  if (Array.isArray(value)) return value;
  if (!value) return fallback;
  try { return typeof value === 'string' ? JSON.parse(value) : value; } catch { return fallback; }
}

export default async function AdminReportDetail({ params }) {
  const token = (await cookies()).get('vsi_admin_session')?.value;
  if (!isAdminSession(token)) redirect('/admin/login');
  const { reference } = await params;
  const sql = neon(process.env.DATABASE_URL);
  const rows = await sql`SELECT * FROM activity_reports WHERE reference = ${reference} LIMIT 1`;
  if (!rows.length) return <main className="page"><div className="shell"><div className="error">Report not found.</div><Link href="/admin/reports">← Back to Reports Inbox</Link></div></main>;
  const report = rows[0];
  const attachments = parseJson(report.attachments);
  const budgetItems = parseJson(report.budget_items);
  const followUps = parseJson(report.follow_up_actions);
  const evidence = parseJson(report.evidence_available);

  return <main className="page">
    <div className="topbar"><div className="topbar-inner"><div className="brand"><img src="/vsi-logo-white.png" alt="Visionary Students Initiative" className="vsi-logo" /></div><span>ACTIVITY REPORT</span><div className="social-links"><a href="https://web.facebook.com/vsizambia" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a href="https://www.linkedin.com/in/visionary-students-initiative-vsi-0a447238/" target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><a href="https://www.instagram.com/vsizambia" target="_blank" rel="noreferrer" aria-label="Instagram">◎</a><a href="https://www.youtube.com/@vsizambia" target="_blank" rel="noreferrer" aria-label="YouTube">▶</a><a href="https://www.vsizambia.org" target="_blank" rel="noreferrer" aria-label="VSI website">↗</a><form action="/api/admin/login" method="post" style={{ marginLeft: 6 }}><button type="submit" style={{ background: 'transparent', border: '1px solid rgba(255,255,255,.5)', color: '#fff', borderRadius: 20, padding: '8px 12px', fontWeight: 800 }}>Sign out</button></form></div></div></div>
    <div className="shell">
      <header className="form-intro"><p><strong>VSI ADMINISTRATION · ACTIVITY REPORT REVIEW</strong><br />Review the complete submitted record, verify supporting evidence, and prepare the report for the next workflow decision.</p></header>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginBottom: 18, flexWrap: 'wrap' }}><div><p className="kicker">ACTIVITY REPORT</p><h1 style={{ margin: 0, color: 'var(--regal-navy)' }}>{report.activity_title}</h1><p style={{ color: 'var(--muted)', marginBottom: 0 }}>{report.reference} · {report.activity_date ? new Date(report.activity_date).toLocaleDateString() : '—'}</p></div><Link href="/admin/reports" className="small-btn" style={{ textDecoration: 'none' }}>← Reports Inbox</Link></div>
      <section className="section"><div className="section-head"><span className="number">01</span><div><h2>Report Overview</h2><p>Core identification and reporting information.</p></div></div><div className="section-body"><div className="grid"><Field label="Activity Title" value={report.activity_title}/><Field label="Activity Type" value={report.activity_type}/><Field label="Directorate" value={report.directorate}/><Field label="Programme" value={report.programme}/><Field label="Project" value={report.project}/><Field label="Activity Code" value={report.activity_code}/><Field label="Activity Date" value={report.activity_date}/><Field label="Venue" value={report.venue}/><Field label="Province" value={report.province}/><Field label="District" value={report.district}/><Field label="Reporter" value={`${report.reporter_full_name || '—'} · ${report.reporter_position || '—'}`}/><Field label="Reporter Contact" value={`${report.reporter_phone || '—'} · ${report.reporter_email || '—'}`}/><Field label="Supervisor" value={`${report.supervisor_full_name || '—'} · ${report.supervisor_position || '—'}`}/><Field label="Funding Source" value={report.funding_source}/><Field label="Donor / Grant" value={`${report.donor_name || '—'} · ${report.grant_title || '—'} · ${report.grant_reference || '—'}`}/><Field label="Description" value={report.activity_description}/></div></div></section>
      <section className="section"><div className="section-head"><span className="number">02</span><div><h2>Activity & Results</h2><p>Implementation, participation, outcomes and learning.</p></div></div><div className="section-body"><div className="grid"><Field label="Target Group" value={report.target_group}/><Field label="Participants" value={`Total ${report.participant_total ?? 0} · Female ${report.participant_female ?? 0} · Male ${report.participant_male ?? 0} · Other ${report.participant_other ?? 0}`}/><Field label="Objectives" value={report.objectives}/><Field label="Activity Delivered" value={report.activity_delivered}/><Field label="Implementation Status" value={report.implementation_status}/><Field label="Implementation Change" value={report.implementation_change}/><Field label="Knowledge / Skills" value={report.knowledge_skills}/><Field label="Key Issues" value={report.key_issues}/><Field label="Participant Feedback" value={report.participant_feedback}/><Field label="Immediate Outcomes" value={report.immediate_outcomes}/><Field label="Notable Achievements" value={report.notable_achievements}/><Field label="Results Evidence" value={report.results_evidence}/><Field label="Overall Assessment" value={report.overall_assessment}/><Field label="Assessment Explanation" value={report.assessment_explanation}/></div></div></section>
      <section className="section"><div className="section-head"><span className="number">03</span><div><h2>Finance & Follow-up</h2><p>Review financial totals and outstanding actions.</p></div></div><div className="section-body"><div className="grid"><Field label="Approved Budget" value={report.approved_budget}/><Field label="Actual Spent" value={report.actual_spent}/><Field label="Budget Status" value={report.budget_status}/><Field label="Overspend Cause" value={report.overspend_cause}/><Field label="Challenges" value={report.challenges}/><Field label="Challenges Addressed" value={report.challenges_addressed}/><Field label="Lessons Learned" value={report.lessons_learned}/><Field label="Future Improvements" value={report.future_improvements}/><Field label="Safeguarding Status" value={report.safeguarding_status}/></div>{budgetItems.length > 0 && <div style={{ marginTop: 20 }}><h3>Budget Items</h3><div className="table-wrap"><table className="money-table"><thead><tr><th>Item</th><th>Approved</th><th>Actual</th></tr></thead><tbody>{budgetItems.map((x,i)=><tr key={i}><td>{x.item || '—'}</td><td>{x.approved || 0}</td><td>{x.actual || 0}</td></tr>)}</tbody></table></div></div>}{followUps.length > 0 && <div style={{ marginTop: 20 }}><h3>Follow-up Actions</h3><div className="table-wrap"><table className="money-table"><thead><tr><th>Action</th><th>Responsible</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{followUps.map((x,i)=><tr key={i}><td>{x.action || '—'}</td><td>{x.responsible || '—'}</td><td>{x.deadline || '—'}</td><td>{x.status || '—'}</td></tr>)}</tbody></table></div></div>}</div></section>
      <section className="section"><div className="section-head"><span className="number">04</span><div><h2>Evidence & Attachments</h2><p>Every uploaded document is listed individually for review.</p></div></div><div className="section-body">{evidence.length > 0 && <div className="options" style={{ marginBottom: 18 }}>{evidence.map((x)=><span className="option" key={x}>{x}</span>)}</div>}{attachments.length ? <div className="vsi-document-table"><div className="vsi-document-row vsi-document-head"><span>Document</span><span>Type / Size</span><span>Open</span></div>{attachments.map((file,i)=><div className="vsi-document-row" key={i}><div className="vsi-document-file"><strong>{file.name || 'Unnamed document'}</strong></div><div>{file.type || 'File'} · {file.size ? `${(Number(file.size)/1024/1024).toFixed(2)} MB` : 'Size unavailable'}</div><div>{file.url ? <a href={file.url} target="_blank" rel="noreferrer" className="small-btn" style={{ display: 'inline-block', textDecoration: 'none' }}>Open ↗</a> : '—'}</div></div>)}</div> : <div className="vsi-document-empty">No uploaded documents were attached to this report.</div>}<p className="hint" style={{ marginTop: 12 }}>Evidence uploaded: {report.evidence_uploaded || '—'} · Photo/media consent: {report.photo_media_consent || '—'}</p></div></section>
      <section className="section"><div className="section-head"><span className="number">05</span><div><h2>Administrative Review</h2><p>Review controls will be wired to the report status workflow after the current record view is verified.</p></div></div><div className="section-body"><div className="notice"><strong>Current stage: Pending Review</strong><br />The report is available for administrative inspection. Approval, return-for-correction and rejection actions will be enabled against the authoritative report status once the review fields are confirmed in the production schema.</div></div></section>
    </div>
  </main>;
}
