import { createHmac, timingSafeEqual } from 'node:crypto';
import { cookies } from 'next/headers';

const COOKIE = 'vsi_admin_session';
const MFA_COOKIE = 'vsi_admin_mfa';
const WINDOW_MS = 15 * 60 * 1000;
const MAX_ATTEMPTS = 10;
const MFA_TTL_MS = 5 * 60 * 1000;
const attempts = new Map();

function sign(value) { return createHmac('sha256', process.env.VSI_SESSION_SECRET || '').update(value).digest('hex'); }
function sameSecret(a,b){const left=Buffer.from(String(a||''));const right=Buffer.from(String(b||''));return left.length===right.length&&timingSafeEqual(left,right);}
function clientKey(request){const forwarded=request.headers.get('x-forwarded-for');return (forwarded?.split(',')[0]?.trim()||request.headers.get('x-real-ip')||'unknown').slice(0,128);}
function isRateLimited(key){const now=Date.now();const entry=attempts.get(key);if(!entry||now-entry.startedAt>=WINDOW_MS){attempts.set(key,{startedAt:now,count:0});return false;}return entry.count>=MAX_ATTEMPTS;}
function recordFailure(key){const now=Date.now();const entry=attempts.get(key);if(!entry||now-entry.startedAt>=WINDOW_MS)attempts.set(key,{startedAt:now,count:1});else entry.count+=1;}
function base32Decode(input){const normalized=String(input||'').toUpperCase().replace(/[^A-Z2-7]/g,'');let bits='';for(const char of normalized){const value='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(char);if(value<0)return null;bits+=value.toString(2).padStart(5,'0');}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)i+=0,bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes);}
function totp(secret,counter){const key=base32Decode(secret);if(!key?.length)return null;const message=Buffer.alloc(8);message.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',key).update(message).digest();const offset=digest[digest.length-1]&15;const binary=((digest[offset]&127)<<24)|(digest[offset+1]<<16)|(digest[offset+2]<<8)|digest[offset+3];return String(binary%1000000).padStart(6,'0');}
function verifyTotp(secret,code){if(!/^\d{6}$/.test(code||''))return false;const counter=Math.floor(Date.now()/30000);for(const delta of [-1,0,1]){const expected=totp(secret,counter+delta);if(expected&&sameSecret(code,expected))return true;}return false;}
function createToken(username,role){const payload=`${username}|${role}|${Date.now()}`;return `${Buffer.from(payload).toString('base64url')}.${sign(payload)}`;}
function createMfaToken(username){const payload=`${username}|${Date.now()}`;return `${Buffer.from(payload).toString('base64url')}.${sign(`mfa|${payload}`)}`;}
function readSignedToken(token,prefix=''){if(!token||!process.env.VSI_SESSION_SECRET)return null;const [encoded,signature]=token.split('.');if(!encoded||!signature)return null;try{const payload=Buffer.from(encoded,'base64url').toString('utf8');const expected=sign(`${prefix}${prefix?'|':''}${payload}`);if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;const parts=payload.split('|');const username=parts[0];const role=prefix?'':parts.length===3?parts[1]:null;const timestamp=Number(parts.length===3?parts[2]:parts[1]);if(!username||!Number.isFinite(timestamp))return null;return {username,role,timestamp};}catch{return null;}}
function credentials(){return [{username:process.env.VSI_AUTH_USERNAME,password:process.env.VSI_ADMIN_PASSWORD,role:'admin',mfa:process.env.VSI_ADMIN_TOTP_SECRET},{username:process.env.VSI_PROGRAMMES_USERNAME,password:process.env.VSI_PROGRAMMES_PASSWORD,role:'programmes',mfa:process.env.VSI_PROGRAMMES_TOTP_SECRET},{username:process.env.VSI_FINANCE_HR_USERNAME,password:process.env.VSI_FINANCE_HR_PASSWORD,role:'finance',mfa:process.env.VSI_FINANCE_HR_TOTP_SECRET}].filter(x=>x.username&&x.password);}
export function getAdminRole(username){return credentials().find(x=>sameSecret(x.username,username))?.role||null;}
function getCredential(username,password){return credentials().find(x=>sameSecret(x.username,username)&&sameSecret(x.password,password))||null;}
export async function POST(request){const key=clientKey(request);if(isRateLimited(key))return Response.json({error:'Too many sign-in attempts. Please try again later.'},{status:429,headers:{'Retry-After':'900'}});try{const body=await request.json();const username=typeof body?.username==='string'?body.username:'';const password=typeof body?.password==='string'?body.password:'';const code=typeof body?.code==='string'?body.code.replace(/\s/g,''):'';if(!process.env.VSI_SESSION_SECRET||credentials().length===0)return Response.json({error:'Admin authentication is not configured.'},{status:503});const store=await cookies();const mfaCookie=store.get(MFA_COOKIE)?.value;if(mfaCookie){const pending=readSignedToken(mfaCookie,'mfa');const account=pending&&credentials().find(x=>sameSecret(x.username,pending.username));if(!pending||Date.now()-pending.timestamp>=MFA_TTL_MS||!account?.mfa||!verifyTotp(account.mfa,code)){recordFailure(key);return Response.json({error:'Invalid verification code.'},{status:401});}attempts.delete(key);store.delete(MFA_COOKIE);store.set(COOKIE,createToken(pending.username,account.role),{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:28800});return Response.json({ok:true,role:account.role});}const account=getCredential(username,password);if(!account){recordFailure(key);return Response.json({error:'Invalid username or password.'},{status:401});}if(account.mfa){store.set(MFA_COOKIE,createMfaToken(username),{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:300});return Response.json({ok:true,requiresMfa:true});}attempts.delete(key);store.set(COOKIE,createToken(username,account.role),{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:28800});return Response.json({ok:true,role:account.role});}catch{recordFailure(key);return Response.json({error:'Unable to sign in.'},{status:400});}}
export async function DELETE(){const store=await cookies();store.delete(COOKIE);store.delete(MFA_COOKIE);return Response.json({ok:true});}
function normalizeAdminRole(role){const value=String(role||'').trim().toLowerCase();if(value==='admin'||value==='super_admin')return 'admin';if(value==='programmes'||value==='programs'||value==='programmes_director')return 'programmes';if(value==='finance'||value==='finance_hr'||value==='finance-&-hr'||value==='finance_and_hr'||value==='finance & hr')return 'finance';return null;}
export function getAdminSession(token){const data=readSignedToken(token);if(!data||Date.now()-data.timestamp>=28800000)return null;const role=normalizeAdminRole(data.role)||normalizeAdminRole(getAdminRole(data.username));if(!role)return null;return {username:data.username,role};}
export function getAdminSessionUsername(token){return getAdminSession(token)?.username||null;}
export function getAdminSessionRole(token){return getAdminSession(token)?.role||null;}
export function isAdminSession(token){return Boolean(getAdminSession(token));}
