'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

const NAV = [
  ['Dashboard', '/admin'], ['Activity Reports', '/admin/reports'], ['Pending Review', '/admin/reports?status=PENDING_REVIEW'],
  ['Approved Reports', '/admin/reports?status=APPROVED'], ['Finance Intelligence', '/admin/finance'], ['MEAL Intelligence', '/admin/meal'],
];
const num = (v) => Number(v ?? 0) || 0;
const first = (o, keys, fallback = '') => keys.map(k => o?.[k]).find(v => v !== undefined && v !== null && v !== '') ?? fallback;
const json = (v, fallback = {}) => { if (!v) return fallback; if (typeof v === 'object') return v; try { return JSON.parse(v); } catch { return fallback; } };
const pct = (n, d) => d ? Math.round((n / d) * 100) : 0;

function Sidebar() { return <aside className="admin-sidebar"><div className="side-brand"><div className="side-logo-wrap"><img src="/vsi-logo-white.png" alt="Visionary Students Initiative" /></div><div><strong>VSI IMS</strong><small>ADMINISTRATION</small></div></div><div className="side-label">WORKSPACE</div><nav>{NAV.slice(0,4).map(([label,href]) => <Link key={label} href={href}><span className="nav-dot" />{label}</Link>)}</nav><div className="side-label intelligence">INTELLIGENCE</div><nav>{NAV.slice(4).map(([label,href]) => <Link key={label} href={href} className={label === 'MEAL Intelligence' ? 'active' : ''}><span className="nav-dot intel-dot" />{label}</Link>)}</nav><div className="side-note">Approved reports are the trusted layer for organisational performance, finance and MEAL intelligence.</div><Link className="back-report" href="/activity-report">Open Activity Report ↗</Link></aside>; }

function breakdown(report) { const a = json(report.attachments, []); const b = a.find(x => x?.category === 'participant-breakdown')?.breakdown || {}; const r = k => num(b[`reached${k}`]); const p = k => num(b[`planned${k}`]); return { children:r('MaleChildren')+r('FemaleChildren'), youth:r('MaleYouth')+r('FemaleYouth'), adult:r('MaleAdult')+r('FemaleAdult'), male:r('MaleChildren')+r('MaleYouth')+r('MaleAdult'), female:r('FemaleChildren')+r('FemaleYouth')+r('FemaleAdult'), pwdMale:r('PwdMaleChildren')+r('PwdMaleYouth')+r('PwdMaleAdult'), pwdFemale:r('PwdFemaleChildren')+r('PwdFemaleYouth')+r('PwdFemaleAdult'), planned:p('MaleChildren')+p('FemaleChildren')+p('MaleYouth')+p('FemaleYouth')+p('MaleAdult')+p('FemaleAdult') }; }
function strings(value, out = []) { if (typeof value === 'string') out.push(value); else if (Array.isArray(value)) value.forEach(v => strings(v,out)); else if (value && typeof value === 'object') Object.values(value).forEach(v => strings(v,out)); return out; }
const demoIcon = { children:'👧', youth:'🧑', adult:'👥', male:'♂', female:'♀', pwd:'♿' };

export default function Phase4Dashboard() {
  const [reports,setReports]=useState([]), [details,setDetails]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [query,setQuery]=useState(''), [filter,setFilter]=useState('All');
  useEffect(()=>{let cancelled=false;(async()=>{try{const res=await fetch('/api/admin/activity-reports',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load MEAL intelligence.');const list=data.reports||[];const full=await Promise.all(list.filter(r=>r.review_status==='APPROVED').map(async r=>{try{const d=await fetch(`/api/admin/activity-reports/${encodeURIComponent(r.reference)}`,{cache:'no-store'});const x=await d.json();return x.report||r}catch{return r}}));if(!cancelled){setReports(list);setDetails(full)}}catch(e){if(!cancelled)setError(e.message)}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
  const stats=useMemo(()=>{const reached=details.reduce((s,r)=>{const b=breakdown(r);return s+(num(first(r,['reached_participant_total','participant_total','participants_reached']))||b.children+b.youth+b.adult)},0);const planned=details.reduce((s,r)=>{const b=breakdown(r);return s+(num(first(r,['planned_participant_total','participant_target','target_participants']))||b.planned)},0);const assessments=details.map(r=>num(r.assessment_score)).filter(v=>v>0);const implemented=details.filter(r=>String(r.implementation_status||'').toLowerCase().includes('fully')).length;const partial=details.filter(r=>String(r.implementation_status||'').toLowerCase().includes('partial')).length;const notImplemented=details.filter(r=>String(r.implementation_status||'').toLowerCase().includes('not implemented')).length;const concerns=details.flatMap(r=>strings(r.safeguarding_status)).filter(s=>/concern identified|requires follow/i.test(s)).length;const evidence=details.filter(r=>r.results_evidence||r.evidence_uploaded).length;const outcomes=details.filter(r=>r.immediate_outcomes||r.notable_achievements).length;return{reached,planned,achievement:pct(reached,planned),assessment:assessments.length?Math.round(assessments.reduce((a,b)=>a+b,0)/assessments.length):0,implemented,partial,notImplemented,concerns,evidence,outcomes}},[details]);
  const demo=useMemo(()=>details.reduce((t,r)=>{const b=breakdown(r);Object.keys(t).forEach(k=>t[k]+=b[k]||0);return t},{children:0,youth:0,adult:0,male:0,female:0,pwdMale:0,pwdFemale:0,planned:0}),[details]);
  const totalPwd=demo.pwdMale+demo.pwdFemale;
  const programmes=useMemo(()=>{const m=new Map();details.forEach(r=>{const p=first(r,['programme','programme_name','programmeName'],'Unspecified');const x=m.get(p)||{name:p,reports:0,reached:0};x.reports++;const b=breakdown(r);x.reached+=num(first(r,['reached_participant_total','participant_total','participants_reached']))||b.children+b.youth+b.adult;m.set(p,x)});return[...m.values()].sort((a,b)=>b.reached-a.reached)},[details]);
  const categories=useMemo(()=>['All',...new Set(details.map(r=>first(r,['programme','programme_name','programmeName'],'Unspecified')))], [details]);
  const filtered=useMemo(()=>details.filter(r=>{const name=first(r,['activity_title','activity_name','activityName'],'Activity');const programme=first(r,['programme','programme_name','programmeName'],'Unspecified');return(!query||`${name} ${programme}`.toLowerCase().includes(query.toLowerCase()))&&(filter==='All'||programme===filter)}),[details,query,filter]);
  const demographicCards=[['children','Children','reached'],['youth','Youth','reached'],['adult','Adults','reached'],['male','Male','all age groups'],['female','Female','all age groups'],['pwd','Persons with Disability (PWD)','reached']];
  const demographicValue=k=>k==='pwd'?totalPwd:demo[k];
  const donutTotal=demo.children+demo.youth+demo.adult;
  const donutSegments=useMemo(()=>{const raw=[['Children',demo.children,'children'],['Youth',demo.youth,'youth'],['Adults',demo.adult,'adult']].filter(x=>x[1]>0);let cursor=0;return raw.map(([name,value,key])=>{const start=cursor;cursor+=donutTotal?value/donutTotal*360:0;return{name,value,key,start,end:cursor,p:donutTotal?pct(value,donutTotal):0}})},[demo,donutTotal]);
  const conic=donutSegments.length?`conic-gradient(${donutSegments.map((s,i)=>`${['#3c6997','#2e8b57','#7657a8'][i]} ${s.start}deg ${s.end}deg`).join(',')})`:'conic-gradient(#dbe5ef 0 360deg)';
  return <div className="phase1-app"><Sidebar/><main className="phase1-main"><header className="phase1-header"><div><div className="phase1-kicker">VSI ADMINISTRATION · MEAL INTELLIGENCE</div><h1>MEAL Intelligence</h1><p>Monitoring, evaluation, accountability and learning signals derived from approved activity reports.</p></div><Link href="/admin/reports?status=APPROVED" className="phase1-action">Approved Reports →</Link></header>{loading&&<div className="phase1-message">Loading live MEAL intelligence…</div>}{error&&<div className="phase1-message error">{error}</div>}{!loading&&!error&&<>
    <section className="phase1-kpis"><div><span>Total Reached</span><strong>{stats.reached.toLocaleString()}</strong><small>Participants reached</small><div className="kpi-footer"><span>◉ {details.length} activities</span><b>{stats.planned?`${stats.achievement}% of target`:'—'}</b></div></div><div><span>Target Achievement</span><strong>{stats.planned?`${stats.achievement}%`:'—'}</strong><small>{stats.reached.toLocaleString()} reached of {stats.planned.toLocaleString()} planned</small><div className="kpi-footer"><span>◎ Target</span><b>{stats.planned?`${stats.reached.toLocaleString()} / ${stats.planned.toLocaleString()}`:'No target'}</b></div></div><div><span>Outcome & Evidence</span><strong>{details.length?`${Math.round((stats.outcomes+stats.evidence)/(details.length*2)*100)}%`:'0%'}</strong><small>Coverage across approved reports</small><div className="kpi-footer"><span>✓ {stats.outcomes} outcomes</span><b>{stats.evidence} evidence</b></div></div></section>
    <section className="phase1-micro"><div><span>👧</span><small>CHILDREN</small><strong>{demo.children.toLocaleString()}</strong></div><div><span>🧑</span><small>YOUTH</small><strong>{demo.youth.toLocaleString()}</strong></div><div><span>👥</span><small>ADULTS</small><strong>{demo.adult.toLocaleString()}</strong></div><div><span>♂</span><small>MALE</small><strong>{demo.male.toLocaleString()}</strong></div><div><span>♀</span><small>FEMALE</small><strong>{demo.female.toLocaleString()}</strong></div><div><span>♿</span><small>PWD</small><strong>{totalPwd.toLocaleString()}</strong></div></section>
    <section className="phase1-grid phase1-bottom-grid">
      <article className="phase1-card wide activity-panel"><div className="phase1-card-head"><div><span>ACTIVITY DETAILS</span><h2>Approved activity reach</h2><p>Click an activity to open its MEAL detail.</p></div><b className="count-badge">{filtered.length}</b></div><div className="filters"><label className="search-box">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search activity or programme" /></label><select value={filter} onChange={e=>setFilter(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="activity-list">{filtered.length?filtered.map((r,i)=>{const name=first(r,['activity_title','activity_name','activityName'],'Activity');const programme=first(r,['programme','programme_name','programmeName'],'Unspecified');const b=breakdown(r);const planned=num(first(r,['planned_participant_total','participant_target','target_participants']))||b.planned;const reached=num(first(r,['reached_participant_total','participant_total','participants_reached']))||b.children+b.youth+b.adult;const achievement=pct(reached,planned);const pwd=b.pwdMale+b.pwdFemale;return <Link href={`/admin/reports/${encodeURIComponent(r.reference)}`} className="meal-activity" key={r.reference||i}><div className="activity-main"><div className="activity-icon">▣</div><div><span className="mini-kicker">ACTIVITY</span><h3>{name}</h3><p>{programme} · {first(r,['project','project_name','projectName'],'Approved activity')}</p></div></div><span className={`status-pill ${achievement>=100?'complete':achievement>0?'progress':'attention'}`}>{achievement>=100?'Target achieved':achievement>0?'In progress':'No reach recorded'}</span><div className="meal-metrics"><div><small>PLANNED</small><strong>{planned.toLocaleString()}</strong></div><div><small>REACHED</small><strong>{reached.toLocaleString()}</strong></div><div><small>VARIANCE</small><strong>{(reached-planned).toLocaleString()}</strong></div></div><div className="meal-progress"><div><span>Target achievement</span><b>{planned?`${achievement}%`:'—'}</b></div><div className="progress-track"><i style={{width:`${Math.min(achievement,100)}%`}} /></div><small>{reached.toLocaleString()} reached · {pwd.toLocaleString()} PWD</small></div><span className="detail-link">View MEAL detail →</span></Link>}) : <div className="phase1-empty">No approved activities match the current filters.</div>}</div></article>
      <article className="phase1-card footprint-panel"><div className="phase1-card-head"><div><span>DISAGGREGATED REACH</span><h2>Demographic footprint</h2><p>Participants reached by age group.</p></div></div><div className="donut-wrap"><div className="donut" style={{background:conic}}><div><strong>{donutTotal.toLocaleString()}</strong><span>TOTAL REACHED</span></div></div></div><div className="donut-legend">{donutSegments.length?donutSegments.map((s,i)=><div key={s.key}><span className={`legend-dot dot-${i}`} /><b>{s.name}</b><strong>{s.value.toLocaleString()}</strong><small>{s.p}%</small></div>):<div className="phase1-empty">No demographic reach recorded.</div>}</div></article>
      <article className="phase1-card wide"><div className="phase1-card-head"><div><span>DISAGGREGATED DEMOGRAPHIC REACH</span><h2>Reach by age, sex and disability</h2><p>Clean participant intelligence across approved activities.</p></div></div><div className="phase1-demographics">{demographicCards.map(([key,label,sub])=><div className={`demo-card demo-${key}`} key={key}><div className="demo-icon" aria-hidden="true">{demoIcon[key]}</div><div className="demo-copy"><small>{label}</small><strong>{demographicValue(key).toLocaleString()}</strong><em>{sub}</em></div></div>)}</div></article>
      <article className="phase1-card"><div className="phase1-card-head"><div><span>IMPLEMENTATION AUDIT</span><h2>Delivery status</h2></div></div><div className="phase1-footprint"><div><strong>Fully implemented</strong><span>Activities delivered as planned</span><b>{stats.implemented}</b></div><div><strong>Partially implemented</strong><span>Activities with deviations</span><b>{stats.partial}</b></div><div><strong>Not implemented</strong><span>Activities not delivered</span><b>{stats.notImplemented}</b></div></div></article>
      <article className="phase1-card"><div className="phase1-card-head"><div><span>RESULTS & OUTCOMES</span><h2>Evidence of change</h2></div></div><div className="alert-grid"><div className="alert"><strong>{stats.outcomes}</strong><small>Reports with outcomes</small></div><div className="alert"><strong>{stats.evidence}</strong><small>Reports with evidence</small></div></div><p className="phase1-safe">Outcome and evidence coverage are calculated from approved report information.</p></article>
      <article className="phase1-card wide"><div className="phase1-card-head"><div><span>PROGRAMME PERFORMANCE</span><h2>Approved reach by programme</h2><p>Programme-level participant footprint.</p></div></div><div className="phase1-footprint">{programmes.length?programmes.map(p=><div key={p.name}><strong>{p.name}</strong><span>{p.reports} approved report{p.reports===1?'':'s'}</span><b>{p.reached.toLocaleString()} participants reached</b></div>):<div className="phase1-empty">No approved programme data yet.</div>}</div></article>
      <article className="phase1-card"><div className="phase1-card-head"><div><span>OVERALL ASSESSMENT</span><h2>Operational effectiveness</h2></div></div><div className="assessment"><div className="assessment-score">{stats.assessment?`${stats.assessment}%`:'—'}</div><div className="assessment-track"><i style={{width:`${stats.assessment}%`}}/></div><p>Average assessment score from approved records.</p></div></article>
      <article className="phase1-card"><div className="phase1-card-head"><div><span>SAFEGUARDING</span><h2>MEAL attention signal</h2></div></div><div className="alert-grid"><div className={stats.concerns?'alert hot':'alert'}><strong>{stats.concerns}</strong><small>Safeguarding attention signals</small></div></div><p className="phase1-safe">Signals are surfaced for administrative follow-up; this view does not replace the safeguarding workflow.</p></article>
    </section></>}</main></div>;
}
