'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

const tabs = ['All Reports', 'Pending Review', 'Approved', 'Returned', 'Rejected'];
const fmt = (value) => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const statusStyle = { 'PENDING REVIEW': { background: '#fff9dc', color: '#6b5600' }, APPROVED: { background: '#e7f6ec', color: '#176b38' }, RETURNED: { background: '#fff9dc', color: '#6b5600' }, REJECTED: { background: '#fff0f0', color: '#9a2525' } };

export default function ReportsClient() {
  const [reports, setReports] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [tab, setTab] = useState('All Reports'); const [query, setQuery] = useState(''); const [deleting, setDeleting] = useState('');
  async function loadReports() { setLoading(true); setError(''); try { const response = await fetch('/api/admin/activity-reports', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load reports.'); setReports(data.reports || []); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { loadReports(); }, []);
  async function logout() { await fetch('/api/admin/login', { method: 'DELETE' }); window.location.href = '/admin/login'; }
  async function deleteReport(reference) { if (!window.confirm(`Delete report ${reference}? It will be soft-deleted and removed from the active register.`)) return; setDeleting(reference); try { const response = await fetch('/api/admin/activity-reports/manage', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reference }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to delete report.'); setReports((items) => items.filter((item) => item.reference !== reference)); } catch (err) { setError(err.message); } finally { setDeleting(''); } }
  const counts = useMemo(() => Object.fromEntries(tabs.map((name) => [name, name === 'All Reports' ? reports.length : reports.filter((r) => (r.review_status || 'PENDING REVIEW') === name.toUpperCase()).length])), [reports]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return reports.filter((report) => { const status = report.review_status || 'PENDING REVIEW'; if (tab !== 'All Reports' && status !== tab.toUpperCase()) return false; if (!q) return true; return [report.reference, report.activity_title, report.directorate, report.programme, report.project, report.reporter_full_name].filter(Boolean).join(' ').toLowerCase().includes(q); }); }, [reports, tab, query]);
  return <main className="page" style={{ minHeight: '100vh' }}>
    <div className="topbar"><div className="topbar-inner"><div className="brand"><img src="/vsi-logo-white.png" alt="Visionary Students Initiative" className="vsi-logo" /></div><span>ACTIVITY REPORT</span><div className="social-links" aria-label="VSI social links"><a href="https://web.facebook.com/vsizambia" target="_blank" rel="noreferrer">f</a><a href="https://www.linkedin.com/in/visionary-students-initiative-vsi-0a447238/" target="_blank" rel="noreferrer">in</a><a href="https://www.instagram.com/vsizambia" target="_blank" rel="noreferrer">◎</a><a href="https://www.youtube.com/@vsizambia" target="_blank" rel="noreferrer">▶</a><a href="https://www.vsizambia.org" target="_blank" rel="noreferrer">↗</a><button onClick={logout} type="button" style={{ marginLeft: 6, background: 'transparent', border: '1px solid rgba(255,255,255,.5)', color: '#fff', borderRadius: 20, padding: '8px 12px', fontWeight: 800, cursor: 'pointer' }}>Sign out</button></div></div></div>
    <div className="shell"><header className="form-intro"><p><strong>VSI ADMINISTRATION · ACTIVITY REPORTS</strong><br />Review, verify, approve and manage activity reports submitted by VSI officers.</p></header>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 22 }}>{tabs.map((item) => <button key={item} type="button" onClick={() => setTab(item)} style={{ border: '1px solid var(--line)', borderRadius: 9, padding: '10px 14px', background: tab === item ? 'var(--regal-navy)' : '#fff', color: tab === item ? '#fff' : 'var(--regal-navy)', fontWeight: 800, cursor: 'pointer' }}>{item} <span style={{ opacity: .75 }}>({counts[item] || 0})</span></button>)}</div>
      <section className="section"><div className="section-head"><span className="number">01</span><div><h2>Dashboard Summary</h2><p>Activity report submission and review queue.</p></div></div><div className="section-body"><div className="grid">{[['TOTAL REPORTS','All Reports','All active submitted reports'],['PENDING REVIEW','Pending Review','Awaiting administrative review'],['APPROVED','Approved','Verified reports'],['RETURNED','Returned','Require corrections'],['REJECTED','Rejected','Not accepted']].map(([label,key,note])=><div key={label} style={{ border:'1px solid var(--line)', borderRadius:12, padding:18, background:'#fff' }}><div className="kicker">{label}</div><strong style={{ display:'block', color:'var(--regal-navy)', fontSize:30 }}>{counts[key] || 0}</strong><span style={{ color:'var(--muted)', fontSize:13 }}>{note}</span></div>)}</div></div></section>
      <section className="section"><div className="section-head"><span className="number">02</span><div><h2>Activity Report Register</h2><p>Open, review, edit or soft-delete submitted reports. Date and time received are recorded automatically.</p></div></div><div className="section-body"><div style={{ marginBottom:18 }}><label>Search reports<input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Reference, activity, programme, project or officer…" /></label></div>{loading&&<div className="vsi-document-empty">Loading reports…</div>}{error&&<div className="error">{error}</div>}{!loading&&!error&&<div className="table-wrap"><table className="money-table" style={{ minWidth:1450 }}><thead><tr><th>Reference</th><th>Activity</th><th>Directorate / Programme</th><th>Project</th><th>Activity Date</th><th>Date & Time Received</th><th>Submitted By</th><th>Status</th><th>Review</th><th>Edit</th><th>Delete</th></tr></thead><tbody>{filtered.map((report)=>{const status=report.review_status||'PENDING REVIEW'; const s=statusStyle[status]||statusStyle['PENDING REVIEW']; return <tr key={report.reference}><td><strong>{report.reference}</strong></td><td><strong>{report.activity_title}</strong></td><td>{report.directorate||'—'} / {report.programme||'—'}</td><td>{report.project||'—'}</td><td>{report.activity_date?new Date(report.activity_date).toLocaleDateString():'—'}</td><td><strong>{fmt(report.received_at)}</strong></td><td>{report.reporter_full_name||'—'}</td><td><span style={{ display:'inline-block', padding:'5px 8px', borderRadius:999, background:s.background, color:s.color, fontWeight:800, fontSize:12 }}>{status}</span></td><td><Link href={`/admin/reports/${encodeURIComponent(report.reference)}`} className="small-btn" style={{ display:'inline-block', textDecoration:'none' }}>Review ↗</Link></td><td><Link href={`/admin/reports/${encodeURIComponent(report.reference)}/edit`} className="small-btn" style={{ display:'inline-block', textDecoration:'none' }}>Edit</Link></td><td><button type="button" onClick={()=>deleteReport(report.reference)} disabled={deleting===report.reference} style={{ border:'1px solid #b42318', color:'#b42318', background:'#fff', borderRadius:8, padding:'8px 10px', fontWeight:800, cursor:deleting===report.reference?'wait':'pointer' }}>{deleting===report.reference?'Deleting…':'Delete'}</button></td></tr>})}{filtered.length===0&&<tr><td colSpan="11" style={{ textAlign:'center', padding:35, color:'var(--muted)' }}>No reports match this view.</td></tr>}</tbody></table></div>}</div></section>
    </div></main>;
}
